'use strict';
const app=document.querySelector('#app');let navigation=0;let user=null;
function el(tag,text,cls){const n=document.createElement(tag);if(text!=null)n.textContent=String(text);if(cls)n.className=cls;return n;}
function append(parent,...children){for(const c of children.flat())if(c)parent.append(c);return parent;}
function button(label,fn){const b=el('button',label);b.type='button';b.addEventListener('click',async()=>{b.disabled=true;try{await fn();}catch(e){showError(e);}finally{b.disabled=false;}});return b;}
function link(label,hash){const a=el('a',label);a.href=hash;return a;}
function showError(error){const n=el('div',error.message||String(error),'error');app.prepend(n);}
async function api(path,method='GET',body){document.querySelector('#busy').textContent='处理中';try{const r=await fetch('/api/v1/'+path,{method,headers:body?{'content-type':'application/json','idempotency-key':crypto.randomUUID()}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin'});const data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;}finally{document.querySelector('#busy').textContent='';}}
function jsonBox(value){const d=el('details');append(d,el('summary','查看结构化数据'),el('pre',JSON.stringify(value,null,2)));return d;}
function field(form,label,name,value='',type='text'){const l=el('label');const i=el('input');i.name=name;i.type=type;i.value=value;append(l,el('span',label),i);form.append(l);return i;}
function form(title,fields,submit){const f=el('form');f.append(el('h3',title));for(const spec of fields)field(f,...spec);const b=el('button','提交');b.type='submit';f.append(b);f.addEventListener('submit',async e=>{e.preventDefault();b.disabled=true;try{await submit(Object.fromEntries(new FormData(f)));}catch(error){showError(error);}finally{b.disabled=false;}});return f;}
function editor(title,value,save){const d=el('details');append(d,el('summary',title));const textarea=el('textarea');textarea.value=JSON.stringify(value,null,2);append(d,textarea,button('保存',async()=>{await save(JSON.parse(textarea.value));await route();}));return d;}
function formatTime(s){if(!s)return'未知';const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toLocaleString();}
function media(url,mime){const img=el('img');img.alt='动态图片';img.loading='lazy';img.src=url;let tries=0;img.addEventListener('error',()=>{if(tries++<3)setTimeout(()=>img.src=url,1000*2**tries);});return img;}
async function ensureUser(){try{user=await api('me');return true;}catch{user=null;login();return false;}}
function login(){app.replaceChildren(el('h2','管理员登录'));app.append(form('登录',[['用户名','username','admin'],['密码','password','','password']],async body=>{await api('login','POST',body);await route();}));}
async function home(){const {data}=await api('streamers?limit=100');app.append(el('h2','主播与开播安排'));const grid=el('div',null,'grid');for(const s of data){const card=el('article');append(card,el('h3',s.name),el('span',s.live_status||'unknown','pill'),el('p',s.live_title||''),el('p',s.predicted_start_at?`下一次：${formatTime(s.predicted_start_at)}${s.forecast_stale?'（已过期）':''}`:'尚无足够证据预测'),el('p',s.forecast_reason||'','muted'),link('动态归档与日程','#streamer/'+encodeURIComponent(s.id)));grid.append(card);}app.append(grid);if(!data.length)app.append(el('p','尚未添加主播，请在后台添加。'));}
async function dynamics(sid){const list=el('section');let cursor=null;const search=form('筛选归档',[['正文关键词','q'],['起始日期（ISO）','from'],['结束日期（ISO）','to']],async q=>{list.replaceChildren();cursor=null;filters=q;await load();});let filters={};const more=button('加载更多动态',load);async function load(){const query=new URLSearchParams({...filters,limit:'20',...(cursor?{cursor}:{})});for(const[k,v]of [...query.entries()])if(!v)query.delete(k);const result=await api(`streamers/${sid}/dynamics?${query}`);for(const d of result.data){const card=el('article');append(card,link(formatTime(d.published_at)+(d.is_pinned?' · 置顶':''),'#dynamic/'+d.id),el('p',d.text),el('p',`${d.type} · ${d.state} · ${d.comment_count||0} 评论`,'muted'));list.append(card);}cursor=result.nextCursor;more.hidden=!cursor;}append(app,search,list,more);await load();}
async function streamer(id){const value=await api('streamers/'+id);const s=value.data;append(app,el('h2',s.name),el('span',s.live_status||'unknown','pill'),el('p',s.live_title||''),jsonBox({forecast:value.forecast,rules:value.rules,exceptions:value.exceptions,evaluations:value.evaluations}));await dynamics(s.id);}
async function dynamic(id){const value=await api('dynamics/'+id);const d=value.data;append(app,el('h2','动态归档'),el('p',formatTime(d.published_at),'muted'),el('p',d.text));for(const m of value.media){if(m.state==='stored')app.append(media('/media/'+m.id));else app.append(el('p',`图片待归档：${m.state}`,'muted'));}try{const raw=JSON.parse(d.raw_excerpt||'{}');if(raw.card)app.append(jsonBox(raw.card));}catch{}
 const source=el('a','在 B 站查看原动态');source.href='https://t.bilibili.com/'+encodeURIComponent(id);source.target='_blank';source.rel='noopener noreferrer';app.append(source);
 const versions=await api('dynamics/'+id+'/revisions?limit=30');if(versions.data.length){const select=el('select');append(select,el('option','选择历史版本'));for(const r of versions.data){const option=el('option',formatTime(r.created_at));option.value=r.id;select.append(option);}const old=el('section');select.addEventListener('change',async()=>{if(!select.value)return;const result=await api(`dynamics/${id}/revisions/${select.value}`);old.replaceChildren(el('p',result.data.text),jsonBox(result.data));});append(app,select,old);}
 const list=el('section');app.append(el('h3','评论与楼中楼'),list);let cursor=null;const more=button('加载更多评论',load);async function load(){const r=await api(`dynamics/${id}/comments?limit=30${cursor?'&cursor='+encodeURIComponent(cursor):''}`);for(const c of r.data){const article=el('article');append(article,el('strong',c.author_name+(c.is_streamer?' · 主播':'')),el('p',c.message),el('small',formatTime(c.published_at)));if(c.reply_count){article.append(button('查看回复',async()=>{const r=await api('comments/'+c.id+'/replies?limit=100');for(const reply of r.data)article.append(el('p',reply.author_name+'：'+reply.message));}));}list.append(article);}cursor=r.nextCursor;more.hidden=!cursor;}app.append(more);await load();}
async function admin(){if(!await ensureUser())return;if(user.forcePasswordChange){app.append(form('请先修改初始化密码',[['新密码（至少10字符）','password','','password']],async body=>{await api('password','POST',body);login();}));return;}
 append(app,el('h2','后台管理'),button('退出登录',async()=>{await api('logout','POST',{});login();}));const status=await api('status');app.append(jsonBox(status));
 app.append(form('添加主播',[['名称','name'],['slug','slug'],['B站UID','biliUid'],['房间号','roomId']],async body=>{await api('streamers','POST',body);await route();}));
 const {data}=await api('streamers?limit=100');for(const s of data){const card=el('article');append(card,el('h3',s.name),link('查看归档','#streamer/'+s.id));const actions=el('div',null,'actions');for(const[op,label]of [['sync','同步最新'],['refresh','刷新半年'],['reanalyze','重新分析'],['reforecast','重新投影日程']])actions.append(button(label,async()=>{const r=await api(`streamers/${s.id}/operations/${op}`,'POST',{});card.append(jsonBox(r));}));append(card,actions,
 editor('修改主播配置',{name:s.name,enabled:!!s.enabled,timezone:s.timezone,livePollSeconds:s.live_poll_seconds,dynamicPollSeconds:s.dynamic_poll_seconds,version:s.version},v=>api('streamers/'+s.id,'PATCH',v)),
 editor('固定周表（替换全部人工规则）',{rules:[]},v=>api(`streamers/${s.id}/rules`,'POST',v)),
 editor('人工开播时间覆盖',{predictedStartAt:new Date(Date.now()+86400000).toISOString(),confidence:100,reason:'人工确认'},v=>api(`streamers/${s.id}/forecast`,'POST',v)));app.append(card);}
 const settings=await api('settings');app.append(editor('模型配置',settings.pi_profile||{provider:'openai',modelId:'gpt-5.4-mini',input:['text','image']},v=>api('settings/pi_profile','POST',{value:v})),editor('SMTP 配置',settings.smtp||{host:'',port:587,secure:false,from:'',to:'',username:''},v=>api('settings/smtp','POST',{value:v})));
 app.append(form('保存密钥（页面不显示原值）',[['名称：pi_api_key / bilibili_cookie / smtp_password','name'],['密钥值','value','','password']],async body=>{await api('secrets/'+encodeURIComponent(body.name),'POST',{value:body.value});await route();}));
 app.append(form('创建管理 API Token',[['名称','name'],['Scopes（逗号分隔）','scopes','status:read,config:read']],async body=>{const result=await api('tokens','POST',{name:body.name,scopes:body.scopes.split(',').map(s=>s.trim())});app.prepend(el('pre','仅此处展示 Token：\n'+result.token));}));
 for(const path of ['jobs','alerts','usage','audit','secrets','tokens','reviews']){const detail=el('details');detail.append(el('summary',path));detail.addEventListener('toggle',async()=>{if(detail.open&&detail.childElementCount===1){try{const r=await api(path+'?limit=30');for(const row of r.data||[]){const entry=el('article');entry.append(jsonBox(row));if(path==='alerts')entry.append(button('确认告警',()=>api(`alerts/${row.id}/acknowledge`,'POST',{})));if(path==='tokens')entry.append(button('撤销Token',()=>api(`tokens/${row.id}/revoke`,'POST',{})));detail.append(entry);}}catch(e){showError(e);}}});app.append(detail);}}
async function drafts(){if(!await ensureUser())return;append(app,el('h2','周表草稿审核'),el('p','只有星期的周表必须选择明确的周一日期；原始动态被编辑后，旧草稿不能确认。'));const r=await api('drafts?limit=100');for(const d of r.data){const card=el('article');append(card,el('h3',d.status+' · '+formatTime(d.created_at)),link('来源动态','#dynamic/'+d.dynamic_id),el('p',d.source_text));let entries;try{entries=JSON.parse(d.entries_json||'[]');}catch{entries=[];}card.append(jsonBox(entries));if(!['confirmed','rejected'].includes(d.status)){const monday=el('input');monday.type='date';const actions=el('div',null,'actions');append(actions,monday,button('确认该周',async()=>{await api(`drafts/${d.id}/confirm`,'POST',{monday:monday.value||null});await route();}),button('拒绝',async()=>{await api(`drafts/${d.id}/reject`,'POST',{});await route();}),button('重新识别',async()=>{await api(`drafts/${d.id}/recognize`,'POST',{});await route();}));append(card,actions,editor('编辑条目',entries,v=>api(`drafts/${d.id}/entries`,'POST',{entries:v})));}app.append(card);}}
async function chat(){if(!await ensureUser())return;app.append(el('h2','后台管理助手'));let conversation=sessionStorage.getItem('vtbm-rust-conversation');if(!conversation){conversation=crypto.randomUUID();sessionStorage.setItem('vtbm-rust-conversation',conversation);}const history=el('section');app.append(history);try{const r=await api('chat/'+conversation+'?limit=30');for(const row of r.data.reverse()){let content;try{content=JSON.parse(row.content_json).content;}catch{content=row.content_json;}history.append(el('p',row.role+'：'+(typeof content==='string'?content:JSON.stringify(content))));}}catch(e){showError(e);}const f=el('form');const input=el('textarea');input.placeholder='描述需要执行的管理操作';const send=el('button','发送');send.type='submit';append(f,input,send);f.addEventListener('submit',async e=>{e.preventDefault();send.disabled=true;try{const prompt=input.value;history.append(el('p','user：'+prompt));input.value='';const r=await api('chat','POST',{prompt,conversationId:conversation});history.append(el('p','assistant：'+r.answer));}catch(error){showError(error);}finally{send.disabled=false;}});app.append(f);}
async function route(){const generation=++navigation;app.replaceChildren();const [name,id]=location.hash.replace(/^#/,'').split('/');try{if(name==='admin')await admin();else if(name==='streamer'&&id)await streamer(decodeURIComponent(id));else if(name==='dynamic'&&id)await dynamic(decodeURIComponent(id));else if(name==='drafts')await drafts();else if(name==='chat')await chat();else await home();if(generation===navigation)app.append(el('footer','Rust 实验后端 · 所有日期以证据和主播时区为准 · 不确定内容保留审核'));}catch(error){showError(error);}}
window.addEventListener('hashchange',route);route();
